CREATE TRIGGER `structurecraft`.`structure_tree_update` AFTER INSERT ON `structures` FOR EACH ROW BEGIN
IF NEW.PARENT_ID IS NULL THEN 
        INSERT INTO `STRUCTURECRAFT`.`STRUCTURE_TREE`(ID, ROOT_ID, ST_DEPTH) VALUES (NEW.ID, NEW.ID, 0);
	UPDATE `STRUCTURECRAFT`.`STRUCTURE_TREE` S SET S.ID = S.ID WHERE S.ID = NEW.ID;
    ELSE
	SET @parent = (SELECT ST.PARENT_ID FROM STRUCTURE_TREE ST WHERE ST.ID = NEW.PARENT_ID);
        SET @root = (SELECT ST.ROOT_ID FROM STRUCTURE_TREE ST WHERE ST.ID = NEW.PARENT_ID);
        SET @depth = (SELECT `ST`.`ST_DEPTH` FROM STRUCTURE_TREE ST WHERE ST.ID = NEW.PARENT_ID);

	INSERT INTO `STRUCTURECRAFT`.`STRUCTURE_TREE` (ID, ROOT_ID, PARENT_ID, ST_DEPTH) VALUES (NEW.ID, @root, @parent, @depth + 1);
	UPDATE `STRUCTURECRAFT`.`STRUCTURE_TREE` S SET S.ID = @v1.ROOT_ID WHERE S.ID = NEW.ID;
END IF;
END