CREATE TABLE IF NOT EXISTS SPATIALS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ORIGIN_X INT,
    ORIGIN_Y INT,
    ORIGIN_Z INT,
    ORIENTATION INT,
    MIN_X INT,
    MIN_Y INT,
    MIN_Z INT,
    MAX_X INT,
    MAX_Y INT,
    MAX_Z INT,    
    SPATIAL_TYPE VARCHAR(30),
    WORLD_NAME VARCHAR(100),
    WORLD_UUID VARCHAR(36)
);
