CREATE TABLE IF NOT EXISTS SPATIALS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ORIGIN_X INT,
    ORIGIN_Y INT,
    ORIGIN_Z INT,
    ORIENTATION INT,
    MIN_Y INT,
    MAX_Y INT,
    envelope GEOMETRY NOT NULL,
    SPATIAL_TYPE VARCHAR(30),
    WORLD_UUID VARCHAR(36),
    ACTIVE BOOLEAN DEFAULT TRUE
);
