SET foreign_key_checks = 0;

DROP TABLE IF EXISTS STRUCTURES;
DROP TABLE IF EXISTS SPATIALS;
DROP TABLE IF EXISTS STRUCTURE_TREE;
DROP TABLE IF EXISTS SETTLERS;
DROP TABLE IF EXISTS STRUCTURE_OWNERSHIPS;
SET foreign_key_checks = 1;
