SET foreign_key_checks = 0;

DROP TABLE IF EXISTS `STRUCTURECRAFT`.`STRUCTURES`;
DROP TABLE IF EXISTS `STRUCTURECRAFT`.`SPATIALS`;
DROP TABLE IF EXISTS `STRUCTURECRAFT`.`STRUCTURE_TREE`;
DROP TABLE IF EXISTS `STRUCTURECRAFT`.`SETTLERS`;
DROP TABLE IF EXISTS `STRUCTURECRAFT`.`STRUCTURE_OWNERSHIPS`;
DROP TABLE IF EXISTS `STRUCTURECRAFT`.`SCHEMATICS`;
DROP TABLE IF EXISTS `STRUCTURECRAFT`.`STRUCTURE_SCHEMATICS`;

SET foreign_key_checks = 1;
